export const FETCH_PLACES = 'FETCH_PLACES'
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS'
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE'
export const SET_CHOOSEN_PLACE = 'SET_CHOOSEN_PLACE'
